wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_size:
  desc: null
  value: 5
channels:
  desc: null
  value:
  - NDVI
  - NDBI
  - NDWI
classes:
  desc: null
  value:
  - LSTN
comparison_loss_factor:
  desc: null
  value: 1.2
comparison_loss_fn:
  desc: null
  value: mse_loss
data_dir:
  desc: null
  value: ../data_source/LONDON_DATASET
dis_dropout:
  desc: null
  value: 0.4
gen_dropout:
  desc: null
  value: 0.4
loss_parameters:
  desc: null
  value: null
lr:
  desc: null
  value: 0.0001
num_epochs:
  desc: null
  value: 20
random_state:
  desc: null
  value: null
save_rate:
  desc: null
  value: 1
task:
  desc: null
  value: reg
test_metric:
  desc: null
  value: mse_loss
test_parameters:
  desc: null
  value: null
test_size:
  desc: null
  value: 0.2
train_size:
  desc: null
  value: null
wandb:
  desc: null
  value: 1

WARNING:root:Found 3088 images in total
WARNING:root:Found 224 groups in root directory
179 training instances, 45 testing instances
Starting training for 20 epochs of 36 training steps and 9 evaluation steps
Traceback (most recent call last):
  File "train_cGAN.py", line 121, in <module>
    train_cGAN(config)
  File "/scratches/mario/hw501/satellite-cGAN/cGAN.py", line 499, in train_cGAN
    epoch_loss = train_cGAN_epoch(
TypeError: train_cGAN_epoch() got an unexpected keyword argument 'wandb'
